name:                hwump
version:             0.1.0.0
github:              "willbush/hwump"
license:             MIT
author:              "Will Bush"
maintainer:          "will.g.bush@gmail.com"
copyright:           "2018 Will Bush"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/willbush/hwump#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- random
- transformers
- vector

library:
  source-dirs: src

executables:
  hwump-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hwump

tests:
  hwump-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hwump
    - hspec
